server:
  port: 8080

spring:
  main:
    banner-mode: OFF
  jackson:
    property-naming-strategy: SNAKE_CASE



---
spring:
  profiles:
    active: "PROD"
---
springdoc:
  swagger-ui:
    suppoerted-submit-metods:
      -get

management:
  metrics:
    export:
      elastic:
        step: 1m
        host: http://localhost:9200

